### ISSUE TITLE
Testbed: allow external modification of physics world

### ISSUE THREAD

**Issue by Vrixyz** [rustsim/nphysics#131]
To continue the discussion from https://discourse.nphysics.org/t/testbed-and-specs-rs-how-to-influence-physics-world/242.

My use case it to use specs.rs with nphysics testbed, allowing modification from a `specs::System`.

I might make pull requests to explore these options:
- lower the ownership requirement of `nphysics::world::World` within testBed (a reference or refcell should be sufficient)
- separate clearly graphics rendering and physics update, so each is optional and can have their own implementation.

**Comment by sebcrozet** [comment]
Fixed by #133
