### ISSUE TITLE
Forces on a multibody

### ISSUE THREAD

**Issue by p23power** [rustsim/nphysics#132]
When using force_generator::ConstantAcceleration on a object::Multibody, the velocity of the body is not impacted.   The object::MultibodyLink::external_forces looks fine.  In  object::Multibody::update_dynamics(), any existing external_force does not seem to be included when calculating the acceleration (accs.gemv_tr).

At the start of the last loop in object::Multibody::update_dynamics() ,you have:
`let mut external_forces;`
I changed this to:
`let mut external_forces = self.rbs[i].external_forces;`
and at the end of the loop, rather that `+=` I use:
`self.rbs[i].external_forces = external_forces;`

With these changes, i seems to work as expected.  Am I missing something?

Many thanks

**Comment by sebcrozet** [comment]
Your proposed changes do make sense. We should also modify `external_forces = Force::new(gravity_force, -gyroscopic) - rb.inertia * acc;` to use a `+=` instead of just `=`.

Do you which to open a PR?

**Comment by sebcrozet** [comment]
This has been fixed on nphysics v0.10.
