### ISSUE TITLE
Sleeping bodies aren't woken up when contacting collider is removed

### ISSUE THREAD

**Issue by cs2dsb** [rustsim/nphysics#154]
I've got a scene where some boxes land on top of a row of other boxes that get removed after a time.

The falling boxes land and go to sleep as expected but when the collider/body supporting them is removed they float there indefinitely. 

I've fixed it by tracking all contact pairs and calling activate_body on any bodies in contact with the collider I'm about to remove and that makes the supported boxes fall as expected.

I was wondering if you'd consider this a bug or something the engine should take care of or, if not, is this a reasonable way to solve it or is there something better (maybe a way to query bodies in a radius around the collider to remove the need to track all contacts?).

Thanks very much :)

**Comment by sebcrozet** [comment]
This is a definitely a bug. It is the task of the physics engine to wake up a body when contacts affecting it disappear.
