### ISSUE TITLE
Testbed shows gray screen until resized

### ISSUE THREAD

**Issue by kirhgoff** [rustsim/nphysics#158]
I was using testbed in my playground project for a while and was quite happy with it. Everything was working perfectly. Then after not using my laptop for a while (I was on a trip) I continued working on my project and discovered that now when I start my application I just see a gray screen (see below). After some exploring, I figured out that everything is working, the window just does not render anything, if you resize it with a mouse, or double-click on the title bar, everything renders perfectly.

I thought something is wrong with my project, but I pulled the last version of nphysics, built it, and run a couple of examples, the same result.

I am working on MacBook Pro, macOS Mojave 10.14

I believe it is hard to figure out what is wrong, but is there some workaround, some method I can call on testbed or something like that, so I don't have to resize my app window everytime I run it?

![image](https://user-images.githubusercontent.com/603097/48682561-eae59300-ebfc-11e8-962d-00e00b80519c.png)

**Comment by sebcrozet** [comment]
If @Ralith is right, then updating the version of `glutin` used by `kiss3d` should fix this. Otherwise, perhaps we could add a `set_size` method to set the window size. This should trigger a resize event.

**Comment by kirhgoff** [comment]
Thanks, will try to play with it and create PR if it would work

**Comment by sebcrozet** [comment]
@kirhgoff The testbeds version 0.3.0 have an updated winit dependency. This should fix your issue though I have not tested personally because I don't have macOS mojave. Please reopen if the problem persist.

**Comment by kirhgoff** [comment]
Thank you, it fixed the issue!
