### ISSUE TITLE
Panic from MoreauJeanSolver with using the Compound shape

### ISSUE THREAD

**Issue by p23power** [rustsim/nphysics#189]
I attach a test case that generates the following crash:
[nphysics_test_case.zip](https://github.com/rustsim/nphysics/files/2907483/nphysics_test_case.zip)

thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', \.cargo\registry\src\github.com-1ecc6299db9ec823\ncollide3d-0.18.2\src\shape\shape_impl.rs:190:22
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:491
   7: std::panicking::continue_panic_fmt
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:398
   8: std::panicking::rust_begin_panic
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libcore\panicking.rs:95
  10: core::panicking::panic_bounds_check
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libcore\panicking.rs:71
  11: ncollide3d::shape::shape_impl::{{impl}}::tangent_cone_contains_dir<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\ncollide3d-0.18.2\src\shape\shape_impl.rs:190
  12: ncollide3d::query::contacts_internal::contact_kinematic::ContactKinematic<f32>::contact<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\ncollide3d-0.18.2\src\query\contacts_internal\contact_kinematic.rs:282
  13: nphysics3d::solver::nonlinear_sor_prox::NonlinearSORProx::update_contact_constraint<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\solver\nonlinear_sor_prox.rs:185
  14: nphysics3d::solver::nonlinear_sor_prox::NonlinearSORProx::solve_unilateral<f32,nalgebra::base::dimension::Dynamic,nalgebra::base::dimension::Dynamic>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\solver\nonlinear_sor_prox.rs:114
  15: nphysics3d::solver::nonlinear_sor_prox::NonlinearSORProx::solve<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\solver\nonlinear_sor_prox.rs:32
  16: nphysics3d::solver::moreau_jean_solver::MoreauJeanSolver<f32>::solve_position_constraints<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\solver\moreau_jean_solver.rs:230
  17: nphysics3d::solver::moreau_jean_solver::MoreauJeanSolver<f32>::step<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\solver\moreau_jean_solver.rs:72
  18: nphysics3d::world::world::World<f32>::step<f32>
             at C:\Users\gbpowerp2\.cargo\registry\src\github.com-1ecc6299db9ec823\nphysics3d-0.10.3\src\world\world.rs:310
  19: nphysics_test_case::main
             at .\src\main.rs:111

**Comment by sebcrozet** [comment]
Hi! Thank you for the test case. I'll attempt to fix this next Saturday.

**Comment by sebcrozet** [comment]
This will be fixed by https://github.com/rustsim/ncollide/pull/268

**Comment by sebcrozet** [comment]
@p23power Note that this will also fix some jitters you may have experienced because of the compound/trimesh collision detection that was buggy.
