### ISSUE TITLE
All examples are running super slow on macOS

### ISSUE THREAD

**Issue by patrickelectric** [rustsim/nphysics#221]
I tried already with release and debug builds, both are super slow running at 0.5fps or something like it.

**Comment by sebcrozet** [comment]
Hi! This is surprising, I do all my developments for nphysics on MacOS and it works fine. Though I guess it depends on your machine characteristics.

- What you did exactly to run the examples in release mode?
- Are you getting the same 0.5 fps when running the online examples: https://www.nphysics.org/demo_all_examples3/
- When running in release mode, can you check the `Profile` checkbox on the right and show us the text that will appears on the top-left of the window?

**Comment by patrickelectric** [comment]
> * What did you do exactly to run the examples in release mode?

![image](https://user-images.githubusercontent.com/1215497/63650271-30e8fd80-c71f-11e9-92df-3ca3164108d0.png)

> * Are you getting the same 0.5 fps when running the online examples:

It works flawless.

> * When running in release mode, can you check the `Profile` checkbox on the right and show us the text that will appears on the top-left of the window?

It's working now, maybe I was running debug binaries after building the release ones!

Thank you for catching up and sorry for the problem! Great project!
