### ISSUE TITLE
.gitignore is missing Intellij files

### ISSUE THREAD

**Issue by jmeggitt** [rustsim/nphysics#227]
The current `.gitignore` is missing configuration files for the Intellij IDE (mainly the `.idea` folder). This is already present in other repositories such as [nalgebra](https://github.com/rustsim/nalgebra/blob/bde8fbe10f26945fd841e046f881a1a2e66c7e2a/.gitignore#L12).

**Comment by Ralith** [comment]
Would it make sense for intellij users to put `/.idea` in their personal global git ignores instead?

**Comment by jmeggitt** [comment]
Probably, but many people don't set one up.

**Comment by sebcrozet** [comment]
@jmeggitt Sounds like a good idea. Would you like to make a PR?
