### ISSUE TITLE
Very slow on macos

### ISSUE THREAD

**Issue by rjpereira** [rustsim/nphysics#247]
I'm a rust newbie and just kicked off the compilation and execution using Jetbrains CLion and usual toolchain on macos Catalina.
The 3d demo compared with the online web demo is much more slower, both in debug and release profile.
Any idea I can't get similar smoothness on desktop app ?

Thanks

**Comment by sebcrozet** [comment]
Hi! Are you certain the "release profile" actually compiles with `--release`?
Did you try to compile without CLion (and with `--release`) and see if there is any difference?

**Comment by rjpereira** [comment]
A good night sleep does miracles: you are right, I added the --release to the "build" action, but the "run" defaulted to the debug build. After adding --release to the "run" it works fine now. Sorry for the confusion.

**Comment by sebcrozet** [comment]
Glad you found the solution!
