### ISSUE TITLE
Custom Broadphase Collision Filters

### ISSUE THREAD

**Issue by rhololkeolke** [rustsim/nphysics#251]
The ability to add custom collision filters, like we can in ncollide, is currently missing. I would like to use this to filter collisions between parent and child links in a multibody. I could potentially do a limited version of this using lots of collision groups, but the filter seems like the better approach.

The docs refer to the ncollide event handling in the [interactions and sensor section ](https://www.nphysics.org/interaction_handling_and_sensors/#interaction-handling). However, looking at the ncollide docs and API it appears this functionality is only available on a CollisionWorld object which isn't used in nphysics.

I see that there is a commented out section to store these types of filters in the geometrical world code.
https://github.com/rustsim/nphysics/blob/70aa53c70cef4b71b81b5811269a1d93b1744923/src/world/geometrical_world.rs#L35-L38

What is the blocker on exposing this feature in nphysics? Depending on the complexity, I may be able to take a stab at exposing this feature.

**Comment by neachdainn** [comment]
I am also very interested in being able to do this.

**Comment by sebcrozet** [comment]
This is fixed and published with the version 0.15.1.
I also added an [example](https://github.com/rustsim/nphysics/blob/master/examples3d/broad_phase_filter3.rs#L16-L40).
