### ISSUE TITLE
Expose nalgebra and ncollide through nphysics

### ISSUE THREAD

**Issue by Bombfuse** [rustsim/nphysics#257]
In order to use nalgebra and ncollide alongside nphysics, you have to make sure you're using the same version ncollide is. We can remove the need to mix and match versions between these crates by exposing ncollide and nalgebra through nphysics.

**Comment by Ralith** [comment]
IMO this is good practice for significant public dependencies in general, even.

**Comment by LiquidityC** [comment]
I have a patch for this if you want a PR :smile:
