### ISSUE TITLE
2d: Moving an object over many ground boxes with width 1, sometimes cause the object to sometimes fly off in the Y-direction?

### ISSUE THREAD

**Issue by jannickj** [rustsim/nphysics#262]
Is there a setting I am missing or is multiple ground boxes not fully supported?

Here is what I mean
```
   # --->
¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
```
Something with only speed in the X-axis will fly off in the y-direction.

```
        #
       /
   --/
¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
```

¤ = Ground  (restituion=0, friction=0.8, density=1600, margin = 0.03)
\# = RigidBody (ccd_enabled, restituion=0, friction=0.8, density=965, margin = 0.01)

**Comment by sebcrozet** [comment]
Hi!

This is a common issue with physics engines, and I am not aware of any solution that handle this nicely for adjacent shapes like that. This won't be fixed any time soon as I believe this would require a decent amount of research work.

**Comment by jannickj** [comment]
Fair enough :) I haven't done a full physics engine myself so I don't know what would be involved :) I assume you could technically do something where static boxes are detected and areas are drawn around them but I can also see how much complexity it would add. That said having a comment somewhere in docs or tutorial could have been helpful.
