### ISSUE TITLE
Is there an example that works with wgpu

### ISSUE THREAD

**Issue by Pointime** [rustsim/nphysics#263]
Just like the title

**Comment by sebcrozet** [comment]
Not that I know of. I have never used wgpu myself.

**Comment by ahirner** [comment]
@Pointime I've made tiny mash-up of `nphysics2d` and `nannou` (which itself uses `wgpu`): https://github.com/ahirner/poly-nou

**Comment by Pointime** [comment]
> @Pointime I've made tiny mash-up of `nphysics2d` and `nannou` (which itself uses `wgpu`): https://github.com/ahirner/poly-nou
Thanks. I need it
