### ISSUE TITLE
Allow user-defined data inside RigidBody

### ISSUE THREAD

**Issue by sebcrozet** [rustsim/nphysics#48]
Original issue from @WaDelma : sebcrozet/ncollide#122.

Currently if you register ContactSignalHandler nphysics World there is no way to detect which entities are colliding.

**Comment by MovingtoMars** [comment]
I was just about to make this issue!

I see two ways to do this:
```
pub struct RigidBody<T> {
    user_data: Option<T>,
    ...
```


```
pub struct RigidBody {
    user_data: Option<Any>,
    ...
```

I'd prefer the first one, however, it would be a breaking change. (Which would be a good time to do any other needed breaking changes IMO.)

**Comment by sebcrozet** [comment]
Yes, I prefer by far the first one as well. I implemented it (locally) yesteday but there is one major flow that makes me hesitant whether or not it is the right approach: compilation times. 

Making the rigid bodies generics cause the `World` to be generic as well. Therefore, the compiler will have to specialize and optimize everything (the world but also every structure and call to `ncollide` as well) when it compiles the user code instead of when it compiles `nphysics` itself. This almost triples the compilation times of `nphysics`' examples.

**Comment by MovingtoMars** [comment]
I can't think of another way that would be sane and give compile-time type safety. I can handle slower compile times in exchange for this feature. There's always [cargo check](https://github.com/rsolomo/cargo-check).

Also, are you building the tests in debug or release mode?

**Comment by sebcrozet** [comment]
@MovingtoMars: I am building in release mode so I guess this explains part of the large compilation times.

For the time being, I'll implement the second option, i.e., `Option<Box<Any>>`. A clean implementation of the first alternative is more complicated if I don't want every single type on `nphysics` to depend on the user data type as well as the rigid bodies.

**Comment by MovingtoMars** [comment]
Ok, sounds good.

**Comment by sebcrozet** [comment]
Done. Though I prefer to keep this issue alive as long as the first option is not implemented (or replaced by something better).

**Comment by Ralith** [comment]
If the generic approach is eventually adopted, I'd argue against making the member `Option<T>`, in favor of `T` (which could perhaps default to `()`). If the user actually needs an optional field, they can still do that, but if you want data on every single body, this way you can accomplish that without a bunch of spurious calls to `unwrap`.

**Comment by Ralith** [comment]
I'd actually like to see this for individual collision shapes within a body, not just entire bodies.

**Comment by sebcrozet** [comment]
@Ralith Actually, each body has only one collision shape. So I guess you are saying that if the shape is a compound shape, then you'd like to attach different user-defined data to each of its parts?

**Comment by Ralith** [comment]
Right. Still an nalgebre interface concern due to the generics, at least.

**Comment by Ralith** [comment]
> Therefore, the compiler will have to specialize and optimize everything (the world but also every structure and call to ncollide as well) when it compiles the user code instead of when it compiles nphysics itself. This almost triples the compilation times of nphysics' examples.

Why doesn't the existing genericness over the float type trigger this?

**Comment by sebcrozet** [comment]
@Ralith The comment you cited dates back from when nphysics wasn't generic wrt. the float type (the user had to choose between f32 and f64 with cargo features). Now that everything is already float-generic I agree it would be better to add a type parameter to rigid bodies instead of using `Any`. I also agree that storing a `T` instead of an `Option<T>` is more ergonomic.

**Comment by Ralith** [comment]
I'm currently working around this by creating a bunch of sensors with the same transforms and shapes as the components of the compound shape, but presumably this forces nphysics to do redundant work.

**Comment by sebcrozet** [comment]
@Merlotec Thank you for reviving this issue. There is no new solution here and this will be addressed for the next release of nphysics.

**Comment by sebcrozet** [comment]
This has been added to nphysics v0.10 as `Option<Box<Any>>`.
