### ISSUE TITLE
Relative orientation forces?

### ISSUE THREAD

**Issue by expenses** [rustsim/nphysics#97]
Hi, currently stuff like `RigidBody::append_lin_force` and `RigidBody::append_force_wrt_point` append a force with respect to the world orientation, not the orientation of the body. This means that even if the object is rotating, it will still accelerate in one direction. Do you think it would be possible to add in forces relative to the orientation of the rigid body?

**Comment by sebcrozet** [comment]
This has been added to nphysics v0.10. See the new force application methods (in particular those with "local" in their names): https://www.nphysics.org/rigid_body_simulations_with_contacts/#one-time-force-application-and-impulses
