### ISSUE TITLE
Learning resources

### ISSUE THREAD

**Issue by TatriX** [rustsim/nphysics#99]
Could you please suggest any resources which can be useful to get more solid idea on how this library should be used. For example how do restitution and frictions work and what values in what ranges should be used. Thanks!

**Comment by sebcrozet** [comment]
Currently, there are no notable learning resources besides the code [examples](https://github.com/sebcrozet/nphysics/tree/master/examples3d). As mentioned in my recent [post](https://www.patreon.com/posts/whats-next-on-0-16264116) I will write a User Guide like the ones I've made for [nalgera](http://nalgebra.org) and [ncollide](http://ncollide.org). Hopefully it will be ready at the end of March or beginning of April.

**Comment by TatriX** [comment]
Awesome!
I'm trying to implement a [simple pong](https://github.com/TatriX/rs-ggez-pong/blob/master/src/main.rs) with nphysics and it would be awesome if you could give me a hint on how can I achieve this.

**Comment by sebcrozet** [comment]
The user guide I mentioned above for nphysics is now [online](https://nphysics.org).
Closing this.

Feel free to open other issues if you need guidance on specific points, or if you have suggestions to improve the guide.
